export const personalData = {
  name: "Fazlul Karim Choudhury",
  title: "Full Stack Developer",
  bio: "Passionate developer with expertise in building modern web applications. I love creating clean, efficient, and user-friendly solutions that solve real-world problems.",
  email: "fazlul0127@gmail.com",
  location: "Bengaluru, India",
  resume: "/v1_resume.pdf",
  socials: {
    github: "https://github.com/FazlulKarimC",
    linkedin: "https://www.linkedin.com/in/fazlul0127/",
    twitter: "https://x.com/FazlulKarim_fk",
  },
}

export const skills = [
  { name: "JavaScript", color: "secondary" },
  { name: "TypeScript", color: "accent" },
  { name: "React", color: "primary" },
  { name: "Next.js", color: "secondary" },
  { name: "Node.js", color: "accent" },
  { name: "Python", color: "primary" },
  { name: "FastAPI", color: "secondary" },
  { name: "Langchain", color: "accent" },
  { name: "Huggingface", color: "primary" },
  { name: "Java", color: "secondary" },
  { name: "C/C++", color: "accent" },
  { name: "HTML/CSS", color: "primary" },
  { name: "PostgreSQL", color: "secondary" },
  { name: "MongoDB", color: "accent" },
  { name: "Tailwind CSS", color: "primary" },
  { name: "Git", color: "secondary" },
  { name: "Docker", color: "accent" },
  { name: "AWS", color: "primary" },
  { name: "Machine Learning", color: "secondary" },
  { name: "Neural Network", color: "accent" },
]

export const experiences = [
  {
    company: "Freelance",
    position: "Full Stack Developer",
    duration: "2024 - Present",
    description: "Turning ideas into clean, production-ready code, available for freelance projects and long-term collaborations.",
  },
  {
    company: "Automatic Data Processing",
    position: "Member Technical",
    duration: "2023 - 2024",
    description: `Built an employee management system with Agile teams using ReactJS, TypeScript, JavaScript (front-end) and Spring Boot, Spring Security, JPA (back-end).
Delivered responsive UI and secure APIs, cutting manual HR tasks by 40% and improving efficiency by 35% for 5,000 users.`,
  },
]

export const education = [
  {
    institution: "North-Eastern Hill University",
    degree: "Bachelor of Technology in Computer Science",
    duration: "2019 - 2023",
  },
]

export const projects = [
  {
    title: "LLMForge",
    description: `A config-driven experimentation platform for systematically comparing LLM reasoning strategies — Naive Prompting, Chain-of-Thought, RAG, and ReAct Agents — with full metrics tracking, a research-grade dashboard, and support for both HuggingFace and Custom Hosted OpenAI-compatible models.`,
    tech: ["Next.js",
        "FastAPI",
        "PostgreSQL",
        "VectorDB",
        "Langchain",
        "Redis",
        "HuggingFace",
        "RAG",
        "ReAct Agents",
        "Chain-of-Thought",
        "Naive Prompting",
        "openai api",
        "ollama"],
    github: "https://github.com/FazlulKarimC/LLM_Forge",
    live: "https://llmforge.vercel.app",
    image: "/LlmForge.png",
  },
  {
    title: "PaperSightAI",
    description: `PaperSight AI is a Next.js web app that uses Google’s Gemini AI to instantly summarize uploaded PDFs, helping researchers, students, and professionals quickly extract key insights from long documents.`,
    tech: ["Next.js",
        "Typescript",
        "PostgreSQL",
        "NeonDB",
        "Langchain",
        "Clerk",
        "TailwindCSS",
        "Shadcn",
        "Node.js",
        "Gemini AI"],
    github: "https://github.com/FazlulKarimC/PaperSight_AI",
    live: "https://papersight.vercel.app",
    image: "/ps_home_page.png",
  },
  {
    title: "BRUTAL",
    description: `BRUTAL is a full-stack e-commerce application that breaks away from the boring, cookie-cutter online stores. Built with a striking Neo Brutalism design language — think thick black borders, offset shadows, and bold color blocking — this isn't just another shop template.`,
    tech: ["Next.js",
        "Typescript",
        "PostgreSQL",
        "NeonDB",
        "Prisma",
        "TailwindCSS",
        "Shadcn",
        "Express.js",
        "Node.js"],
    github: "https://github.com/FazlulKarimC/BRUTAL-e-commerce",
    live: "https://brutalkart.vercel.app/",
    image: "/Brutal.png",
  },
  {
    title: "QuickPay",
    description: "PayTM-like full-stack payment app with secure auth, transactions, and bank linking. Educational payment gateway project built with a Turborepo monorepo and a single Next.js app.",
    tech: ["Next.js",
        "Typescript",
        "PostgreSQL",
        "Prisma",
        "TailwindCSS",
        "WebHooks",
        "NextAuth.js",
        "Node.js"],
    github: "https://github.com/FazlulKarimC/QuickPay",
    live: "https://quickpaay.vercel.app/",
    image: "/quickpaay.png",
  },
  {
    title: "Psychiatric Diagnosis",
    description: "A full-stack web application for mental health screening based on the DASS-42 (Depression Anxiety Stress Scales) questionnaire. This project demonstrates production-ready ML deployment with proper evaluation metrics, ethical considerations, and modern web technologies.",
    tech: ["Python",
        "Machine Learning",
        "Scikit-learn",
        "Matplotlib",
        "NumPy",
        "Pandas",
        "Jupyter",
        "Git",
        "fastapi",],
    github: "https://github.com/FazlulKarimC/Detection-of-Psychiatric-Disorder-using-ML",
    live: "https://neurostat.vercel.app/",
    image: "/pdd.png",
  },
  {
    title: "AI Pothole Detection",
    description: "A research-oriented computer vision system for automated pothole detection, featuring a systematic comparison of YOLO architectures and a production-grade inference pipeline.",
    tech: ["Python",
        "Machine Learning",
        "Computer Vision",
        "YOLO",
        "OpenCV",
        "Matplotlib",
        "NumPy",
        "Pandas",
        "Jupyter",
        "Git",
        "fastapi"],
    github: "https://github.com/FazlulKarimC/Pothole-detection-using-AI",
    live: "https://potholescan.vercel.app/",
    image: "/pothole.png",
  },
]
